# Generated by Django 3.0.8 on 2020-09-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_auto_20200925_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('E', 'Electric'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
